version: '3.9'
services:
  npm:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [npm]
    command: [run, preview]
    ports:
      - '4001:4001'
    user: '${UID:-1000}:${GID:-1000}'
    environment:
      NPM_CONFIG_UPDATE_NOTIFIER: false

volumes:
  no-agent:
    driver: local
